name: story_app
description: App de teste para rodar no iOS usando Codemagic
publish_to: "none"

version: 1.2.73+19

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/dicas_missao.json
    - assets/brinde_semana.json
    - assets/rayanne.jpg
