name: story_app
description: App de teste para rodar no iOS usando Codemagic
publish_to: "none"

version: 1.2.74+20

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # IA (Gemini)
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/dicas_missao.json
    - assets/brinde_semana.json
    - assets/rayanne.jpg
