name: story_app
description: App de teste para rodar no iOS usando Codemagic
publish_to: "none"

version: 1.2.187+34

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0   # ou a versÃ£o mais recente do pub.dev
  flutter_local_notifications: ^17.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  timezone: ^0.9.2

  # IA (Gemini)
  google_generative_ai: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app_icons/
    - assets/dicas_missao.json
    - assets/brinde_semana.json
    - assets/rayanne.jpg
    - assets/sounds/roulette_spin.mp3
    - assets/audio/piano/

flutter_launcher_icons:
    android: false
    ios: true
    image_path_ios: "assets/app_icons/icon.png"
